"""``mnem init`` - first-run wizard.

Output class: interactive (rejects --json with a pointer to a
machine-readable alternative; the wizard never makes sense in a
machine context because it prompts and writes files).

Behavior (rewritten 2026-05-13):

1. Confirm intent. Show what will be created and where.
2. Detect sources via mnem.sources.run_all().
3. Resolve each tool's config:
   - ``yaams``: if ``~/.config/yaams/config.yaml`` exists, reuse in
     place. Else (greenfield) generate one from probe results and
     write it to the canonical location (not a private mnem copy).
   - ``cognitive-ledger``: if ``~/.config/cognitive-ledger/config.yaml``
     exists, record the path. Else print a hint to run ``ledger init``
     and leave the pointer empty.
   - ``owa-piggy``: if ``~/.config/owa-piggy/profiles.conf`` exists,
     record the path. Else print a hint to run ``owa-piggy setup``
     and leave the pointer empty.
4. Write the master ``$XDG_CONFIG_HOME/mnem/config.yaml`` with the
   resolved tool paths and mnem-specific settings.
5. Run ``yaams setup``, ``yaams init-db``, ``yaams ingest --dry-run``
   if yaams is on PATH.
6. Print three suggested next commands.

Idempotent: re-running probes again. The master config is overwritten
unless ``--force`` is omitted *and* the existing content is
unchanged; the user is prompted on conflict.
"""

from __future__ import annotations

import subprocess
from pathlib import Path

import click

from mnem.config import (
  canonical_ledger_config,
  canonical_owa_piggy_config,
  canonical_yaams_config,
  config_dir,
  data_root_default,
  master_config_path,
  render_master,
)
from mnem.sources import ProbeResult, run_all


def _existing_yaams_values(probes: list[ProbeResult]) -> dict:
  """Pull through values from a pre-existing standalone yaams config."""
  for p in probes:
    if p.name == "existing_yaams_config" and p.enabled:
      return p.extras.get("parsed") or {}
  return {}


def _build_yaams_config(probes: list[ProbeResult]) -> str:
  """Generate a yaams config seeded from probe results.

  Used only in the greenfield case (no ``~/.config/yaams/config.yaml``
  on disk). Schema mirrors yaams' own ``config.yaml.example``.
  """
  data = data_root_default()
  db_path = data / "yaams" / "data.db"
  by_name = {p.name: p for p in probes}

  def _probe(name: str) -> ProbeResult:
    return by_name.get(name, ProbeResult(name, False, "not probed"))

  imessage = _probe("imessage")
  email = _probe("email")
  signal = _probe("signal")
  github = _probe("github")
  notes = _probe("notes")
  tier2 = _probe("tier2_ledger")
  owa = _probe("owa_piggy")

  owa_profiles = owa.extras.get("profiles", []) if owa.enabled else []

  existing = _existing_yaams_values(probes)
  ex_ingest = (existing.get("ingest") or {}) if isinstance(existing, dict) else {}
  ex_email = ex_ingest.get("email") or {}
  ex_github = ex_ingest.get("github") or {}
  ex_notes = ex_ingest.get("notes") or {}
  ex_tier2 = ex_ingest.get("tier2_ledger") or {}
  ex_calendar = ex_ingest.get("calendar") or {}
  ex_teams = ex_ingest.get("teams") or {}

  github_username = ex_github.get("username") or github.extras.get("username") or ""
  user_addresses = ex_email.get("user_addresses") or []
  notes_vault = ex_notes.get("vault_path") or notes.extras.get("vault_path", "~/Documents/Obsidian")
  tier2_notes = ex_tier2.get("notes_path") or tier2.extras.get("notes_path", "~/.config/cognitive-ledger/notes")
  calendar_profiles = ex_calendar.get("profiles") or owa_profiles
  teams_profiles = ex_teams.get("profiles") or owa_profiles
  calendar_enabled = bool(ex_calendar.get("enabled")) if ex_calendar else False
  teams_enabled = bool(ex_teams.get("enabled")) if ex_teams else False

  def _bool(b: bool) -> str:
    return "true" if b else "false"

  def _hint_line(p: ProbeResult) -> str:
    if p.enabled:
      return f"# {p.reason}"
    if p.hint:
      return f"# disabled: {p.reason}\n    # hint: {p.hint}"
    return f"# disabled: {p.reason}"

  yaml = f"""# Generated by `mnem init` v{_mnem_version()}. Edit freely.
#
# `enabled: true/false` per source is the toggle. The other keys
# are tool-specific defaults the probe detected. Re-run `mnem init`
# any time to refresh detection (existing config is preserved
# unless you opt in to overwriting).

db_path: {db_path}

ingest:
  since: '2025-01-01T00:00:00Z'

  imessage:
    {_hint_line(imessage)}
    enabled: {_bool(imessage.enabled)}
    chat_db_path: {imessage.extras.get("chat_db_path", "~/Library/Messages/chat.db")}

  email:
    {_hint_line(email)}
    enabled: {_bool(email.enabled)}
    sources: {ex_email.get('sources') or []}   # add Apple Mail directories or .mbox files manually
    user_addresses: {user_addresses}

  signal:
    {_hint_line(signal)}
    enabled: {_bool(signal.enabled)}
    signal_dir: {signal.extras.get("signal_dir", "~/Library/Application Support/Signal")}
    include_attachments: true

  notes:
    {_hint_line(notes)}
    enabled: {_bool(notes.enabled or bool(ex_notes.get('enabled')))}
    vault_path: {notes_vault}

  tier2_ledger:
    {_hint_line(tier2)}
    enabled: {_bool(tier2.enabled or bool(ex_tier2.get('enabled')))}
    notes_path: {tier2_notes}

  github:
    {_hint_line(github)}
    enabled: {_bool(github.enabled)}
    username: '{github_username}'   # set your GitHub username here

  # Teams + calendar consume owa-piggy profiles. Add per-profile
  # blocks if you ingest Teams or calendar data.
  teams:
    enabled: {_bool(teams_enabled)}
    profiles: {teams_profiles}

  calendar:
    enabled: {_bool(calendar_enabled)}
    profiles: {calendar_profiles}

embed:
  model: BAAI/bge-m3
  dimension: 1024

entities:
  spacy_model: xx_ent_wiki_sm
  dictionary: []
"""
  return yaml


def _mnem_version() -> str:
  from mnem import __version__
  return __version__


def _yes(prompt: str, default: bool = True) -> bool:
  suffix = "[Y/n]" if default else "[y/N]"
  ans = click.prompt(f"{prompt} {suffix}", default="", show_default=False).strip().lower()
  if not ans:
    return default
  return ans in ("y", "yes")


def _print_probe_summary(probes: list[ProbeResult]) -> None:
  click.echo("\nSources detected:")
  for p in probes:
    if p.name == "existing_yaams_config":
      continue  # reported separately as a config-reuse prompt
    marker = "+" if p.enabled else "."
    click.echo(f"  {marker} {p.name:<16} {p.reason}")
    if not p.enabled and p.hint:
      click.echo(f"      hint: {p.hint}")


def _which_or_warn(binary: str) -> str | None:
  import shutil
  resolved = shutil.which(binary)
  if not resolved:
    click.echo(f"  ! {binary} not on PATH; skipping", err=True)
  return resolved


def _run_step(label: str, argv: list[str]) -> int:
  click.echo(f"\n-> {label}")
  result = subprocess.run(argv, capture_output=False)
  return result.returncode


def _resolve_yaams_config(probes: list[ProbeResult], *, force: bool) -> Path | None:
  """Decide which yaams config path to record in the master config.

  Returns the resolved path, or None if the user declined to set one.
  Side effects: may write ``~/.config/yaams/config.yaml`` in the
  greenfield case.
  """
  canonical = canonical_yaams_config()
  if canonical.is_file():
    click.echo(f"\n+ yaams config already at {canonical}; reusing in place.")
    return canonical

  click.echo(f"\n. no yaams config at {canonical}.")
  if not _yes("Generate one now from detected sources?", default=True):
    click.echo("  skipped; you can run `mnem init` again after creating one.")
    return None
  canonical.parent.mkdir(parents=True, exist_ok=True)
  canonical.write_text(_build_yaams_config(probes), encoding="utf-8")
  click.echo(f"  wrote {canonical}")
  return canonical


def _resolve_ledger_config() -> Path | None:
  canonical = canonical_ledger_config()
  if canonical.is_file():
    click.echo(f"+ cognitive-ledger config at {canonical}; reusing in place.")
    return canonical
  click.echo(
    f". no cognitive-ledger config at {canonical}.\n"
    "    hint: `ledger init --root <root>` to create one, then re-run `mnem init`."
  )
  return None


def _resolve_owa_piggy_config() -> Path | None:
  canonical = canonical_owa_piggy_config()
  if canonical.is_file():
    click.echo(f"+ owa-piggy config at {canonical}; reusing in place.")
    return canonical
  click.echo(
    f". no owa-piggy config at {canonical}.\n"
    "    hint: `owa-piggy setup --profile <alias> --email <addr>` to create one."
  )
  return None


def run(as_json: bool, *, force: bool = False) -> int:
  if as_json:
    click.echo(
      "mnem init is an interactive command; --json is rejected. "
      "Use `mnem doctor --json` to inspect suite state instead.",
      err=True,
    )
    return 1

  master = master_config_path()
  data = data_root_default()

  click.echo(f"mnem init v{_mnem_version()}")
  click.echo("This wizard:")
  click.echo("  1. probes for ingest sources")
  click.echo(f"  2. writes {master}")
  click.echo(f"  3. uses {data} as the data root (override with MNEM_HOME)")
  click.echo("  4. runs yaams setup, init-db, and ingest --dry-run")
  if not _yes("\nContinue?"):
    click.echo("Aborted.")
    return 0

  # --- Detect ---------------------------------------------------------
  probes = run_all()
  _print_probe_summary(probes)

  # --- Resolve per-tool config paths ---------------------------------
  config_dir().mkdir(parents=True, exist_ok=True)
  data.mkdir(parents=True, exist_ok=True)

  yaams_cfg = _resolve_yaams_config(probes, force=force)
  ledger_cfg = _resolve_ledger_config()
  owa_cfg = _resolve_owa_piggy_config()

  # --- Write master config -------------------------------------------
  body = render_master(
    version=_mnem_version(),
    data_root=data,
    yaams_config=yaams_cfg,
    ledger_config=ledger_cfg,
    owa_piggy_config=owa_cfg,
  )
  if master.is_file() and not force:
    existing_body = master.read_text(encoding="utf-8")
    if existing_body == body:
      click.echo(f"\n{master} already up to date.")
    else:
      click.echo(f"\nMaster config already exists at {master}")
      if not _yes("Overwrite?", default=False):
        click.echo("Keeping existing master config.")
      else:
        master.write_text(body, encoding="utf-8")
        click.echo(f"  wrote {master}")
  else:
    master.write_text(body, encoding="utf-8")
    click.echo(f"\nWrote {master}")

  # --- Run downstream setup ------------------------------------------
  if yaams_cfg is not None:
    yaams = _which_or_warn("yaams")
    if yaams:
      _run_step("yaams setup (install spaCy models if needed)", [yaams, "setup", "--config", str(yaams_cfg)])
      _run_step("yaams init-db", [yaams, "init-db", "--config", str(yaams_cfg)])
      _run_step("yaams ingest --dry-run", [yaams, "ingest", "--dry-run", "--config", str(yaams_cfg)])

  click.echo("\nDone. Suggested next commands:")
  click.echo("  $ mnem ingest")
  click.echo('  $ mnem query "what did we decide about ..."')
  click.echo("  $ mnem hello")
  return 0
