"""``mnem init`` - first-run wizard.

Output class: interactive (rejects --json with a pointer to a
machine-readable alternative; the wizard never makes sense in a
machine context because it prompts and writes files).

Flow per the three-pillar spec in mnem_plan.md:

1. Confirm intent. Show what will be created and where.
2. Detect sources via mnem.sources.run_all().
3. Generate $XDG_CONFIG_HOME/mnem/yaams/config.yaml with explicit
   enabled: true/false per source.
4. Run `yaams setup` (no-op if models already installed).
5. Run `yaams init-db`.
6. Run `yaams ingest --dry-run` and show the count summary.
7. Print three suggested next commands.

Idempotent: re-running probes again, leaves existing config
untouched unless the user opts in.
"""

from __future__ import annotations

import os
import subprocess
import sys
from pathlib import Path

import click

from mnem.sources import ProbeResult, run_all


def _config_dir() -> Path:
  xdg = os.environ.get("XDG_CONFIG_HOME")
  base = Path(xdg) if xdg else Path.home() / ".config"
  return base / "mnem"


def _yaams_config_path() -> Path:
  return _config_dir() / "yaams" / "config.yaml"


def _data_dir() -> Path:
  mnem_home = os.environ.get("MNEM_HOME")
  return Path(mnem_home) if mnem_home else Path.home() / ".local" / "share" / "mnem"


def _existing_yaams_values(probes: list[ProbeResult]) -> dict:
  """Pull through values from a pre-existing standalone yaams config.

  Returned dict mirrors the keys we hand to `_build_yaams_config` for
  seeding: github username, notes vault_path, mail user_addresses, calendar
  profiles, signal flags, ledger paths. Empty dict if no parseable existing
  config (the caller then falls back to probe defaults).
  """
  for p in probes:
    if p.name == "existing_yaams_config" and p.enabled:
      return p.extras.get("parsed") or {}
  return {}


def _build_yaams_config(probes: list[ProbeResult]) -> str:
  """Hand-roll YAML so we don't add a PyYAML dependency to mnem.

  The schema follows YAAMS' existing config.yaml.example: every
  source under `ingest.<name>` carries an explicit `enabled` flag
  plus tool-specific keys. A leading comment block explains the
  shape and where to edit if probe detection got it wrong.

  When a pre-existing standalone yaams config is detected and parseable, we
  seed values from it (github username, mail user_addresses, notes vault_path,
  calendar/teams profiles) so the user doesn't lose curated state by going
  through `mnem init`.
  """
  data = _data_dir()
  db_path = data / "yaams" / "data.db"
  by_name = {p.name: p for p in probes}

  def _probe(name: str) -> ProbeResult:
    return by_name.get(name, ProbeResult(name, False, "not probed"))

  imessage = _probe("imessage")
  email = _probe("email")
  signal = _probe("signal")
  github = _probe("github")
  notes = _probe("notes")
  tier2 = _probe("tier2_ledger")
  owa = _probe("owa_piggy")

  owa_profiles = owa.extras.get("profiles", []) if owa.enabled else []

  existing = _existing_yaams_values(probes)
  ex_ingest = (existing.get("ingest") or {}) if isinstance(existing, dict) else {}
  ex_email = ex_ingest.get("email") or {}
  ex_github = ex_ingest.get("github") or {}
  ex_notes = ex_ingest.get("notes") or {}
  ex_tier2 = ex_ingest.get("tier2_ledger") or {}
  ex_calendar = ex_ingest.get("calendar") or {}
  ex_teams = ex_ingest.get("teams") or {}

  github_username = ex_github.get("username") or github.extras.get("username") or ""
  user_addresses = ex_email.get("user_addresses") or []
  notes_vault = ex_notes.get("vault_path") or notes.extras.get("vault_path", "~/Documents/Obsidian")
  tier2_notes = ex_tier2.get("notes_path") or tier2.extras.get("notes_path", "~/.config/cognitive-ledger/notes")
  calendar_profiles = ex_calendar.get("profiles") or owa_profiles
  teams_profiles = ex_teams.get("profiles") or owa_profiles
  calendar_enabled = bool(ex_calendar.get("enabled")) if ex_calendar else False
  teams_enabled = bool(ex_teams.get("enabled")) if ex_teams else False

  def _bool(b: bool) -> str:
    return "true" if b else "false"

  def _hint_line(p: ProbeResult) -> str:
    if p.enabled:
      return f"# {p.reason}"
    if p.hint:
      return f"# disabled: {p.reason}\n    # hint: {p.hint}"
    return f"# disabled: {p.reason}"

  yaml = f"""# Generated by `mnem init` v{_mnem_version()}. Edit freely.
#
# `enabled: true/false` per source is the toggle. The other keys
# are tool-specific defaults the probe detected. Re-run `mnem init`
# any time to refresh detection (existing config is preserved
# unless you opt in to overwriting).

db_path: {db_path}

ingest:
  since: '2025-01-01T00:00:00Z'

  imessage:
    {_hint_line(imessage)}
    enabled: {_bool(imessage.enabled)}
    chat_db_path: {imessage.extras.get("chat_db_path", "~/Library/Messages/chat.db")}

  email:
    {_hint_line(email)}
    enabled: {_bool(email.enabled)}
    sources: {ex_email.get('sources') or []}   # add Apple Mail directories or .mbox files manually
    user_addresses: {user_addresses}

  signal:
    {_hint_line(signal)}
    enabled: {_bool(signal.enabled)}
    signal_dir: {signal.extras.get("signal_dir", "~/Library/Application Support/Signal")}
    include_attachments: true

  notes:
    {_hint_line(notes)}
    enabled: {_bool(notes.enabled or bool(ex_notes.get('enabled')))}
    vault_path: {notes_vault}

  tier2_ledger:
    {_hint_line(tier2)}
    enabled: {_bool(tier2.enabled or bool(ex_tier2.get('enabled')))}
    notes_path: {tier2_notes}

  github:
    {_hint_line(github)}
    enabled: {_bool(github.enabled)}
    username: '{github_username}'   # set your GitHub username here

  # Teams + calendar consume owa-piggy profiles. Add per-profile
  # blocks if you ingest Teams or calendar data.
  teams:
    enabled: {_bool(teams_enabled)}
    profiles: {teams_profiles}

  calendar:
    enabled: {_bool(calendar_enabled)}
    profiles: {calendar_profiles}

embed:
  model: BAAI/bge-m3
  dimension: 1024

entities:
  spacy_model: xx_ent_wiki_sm
  dictionary: []
"""
  return yaml


def _mnem_version() -> str:
  from mnem import __version__
  return __version__


def _yes(prompt: str, default: bool = True) -> bool:
  suffix = "[Y/n]" if default else "[y/N]"
  ans = click.prompt(f"{prompt} {suffix}", default="", show_default=False).strip().lower()
  if not ans:
    return default
  return ans in ("y", "yes")


def _print_probe_summary(probes: list[ProbeResult]) -> None:
  click.echo("\nSources detected:")
  for p in probes:
    if p.name == "existing_yaams_config":
      continue  # reported separately as a config-reuse prompt
    marker = "+" if p.enabled else "."
    click.echo(f"  {marker} {p.name:<16} {p.reason}")
    if not p.enabled and p.hint:
      click.echo(f"      hint: {p.hint}")


def _which_or_warn(binary: str) -> str | None:
  import shutil
  resolved = shutil.which(binary)
  if not resolved:
    click.echo(f"  ! {binary} not on PATH; skipping", err=True)
  return resolved


def _run_step(label: str, argv: list[str]) -> int:
  click.echo(f"\n-> {label}")
  result = subprocess.run(argv, capture_output=False)
  return result.returncode


def run(as_json: bool, *, force: bool = False) -> int:
  if as_json:
    click.echo(
      "mnem init is an interactive command; --json is rejected. "
      "Use `mnem doctor --json` to inspect suite state instead.",
      err=True,
    )
    return 1

  click.echo(f"mnem init v{_mnem_version()}")
  click.echo("This wizard:")
  click.echo("  1. probes for ingest sources")
  click.echo(f"  2. writes {_yaams_config_path()}")
  click.echo(f"  3. uses {_data_dir()} as the data root (override with MNEM_HOME)")
  click.echo("  4. runs yaams setup, init-db, and ingest --dry-run")
  if not _yes("\nContinue?"):
    click.echo("Aborted.")
    return 0

  # --- Detect ---------------------------------------------------------
  probes = run_all()
  _print_probe_summary(probes)

  # --- Pick the config we will hand to yaams --------------------------
  # Three cases:
  #   1. A standalone yaams config already exists at ~/.config/yaams/config.yaml.
  #      Default is to reuse it in place. Mnem won't touch it.
  #   2. No standalone config, but mnem has written one before. Keep unless
  #      the user opts in to overwrite (or --force was passed).
  #   3. Greenfield. Write a fresh config seeded from probes.
  cfg_path = _yaams_config_path()
  cfg_path.parent.mkdir(parents=True, exist_ok=True)
  data = _data_dir()
  data.mkdir(parents=True, exist_ok=True)

  existing_probe = next((p for p in probes if p.name == "existing_yaams_config" and p.enabled), None)
  existing_cfg_path = Path(existing_probe.extras["path"]) if existing_probe else None

  if existing_cfg_path and existing_cfg_path != cfg_path:
    click.echo(f"\nDetected existing yaams config at {existing_cfg_path}")
    if existing_probe and "parse_note" in existing_probe.extras:
      click.echo(f"  note: {existing_probe.extras['parse_note']}")
    if _yes("Reuse this config in place (recommended)?", default=True):
      cfg_path = existing_cfg_path
      click.echo(f"Using {cfg_path}")
    else:
      click.echo("Generating a separate mnem-managed config.")
      if cfg_path.is_file() and not force:
        click.echo(f"Config already exists at {cfg_path}")
        if not _yes("Overwrite?", default=False):
          click.echo("Keeping existing mnem-managed config.")
        else:
          cfg_path.write_text(_build_yaams_config(probes), encoding="utf-8")
          click.echo(f"  wrote {cfg_path} (seeded from {existing_cfg_path})")
      else:
        cfg_path.write_text(_build_yaams_config(probes), encoding="utf-8")
        click.echo(f"Wrote {cfg_path} (seeded from {existing_cfg_path})")
  elif cfg_path.is_file() and not force:
    click.echo(f"\nConfig already exists at {cfg_path}")
    if not _yes("Overwrite?", default=False):
      click.echo("Keeping existing config.")
    else:
      cfg_path.write_text(_build_yaams_config(probes), encoding="utf-8")
      click.echo(f"  wrote {cfg_path}")
  else:
    cfg_path.write_text(_build_yaams_config(probes), encoding="utf-8")
    click.echo(f"\nWrote {cfg_path}")

  # --- Run downstream setup ------------------------------------------
  yaams = _which_or_warn("yaams")
  if yaams:
    _run_step("yaams setup (install spaCy models if needed)", [yaams, "setup", "--config", str(cfg_path)])
    _run_step("yaams init-db", [yaams, "init-db", "--config", str(cfg_path)])
    _run_step("yaams ingest --dry-run", [yaams, "ingest", "--dry-run", "--config", str(cfg_path)])

  click.echo("\nDone. Suggested next commands:")
  click.echo("  $ mnem ingest")
  click.echo('  $ mnem query "what did we decide about ..."')
  click.echo("  $ mnem hello")
  return 0
